# fly.toml app configuration file generated for native-jibber on 2025-01-02T15:29:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'native-jibber'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
